jobs:
- job:
  displayName: ubuntu-16.04
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - bash: conda create --yes --quiet --name myEnvironment
    displayName: Create Anaconda environment

  - bash: |
      source activate myEnvironment
      conda install --yes --quiet --name myEnvironment python=$PYTHON_VERSION
      conda update --all --yes
      pip install pytest pytest-azurepipelines
    displayName: Install Anaconda packages
    
  - bash: |
      source activate myEnvironment
      conda install boost-cpp -c conda-forge --yes
      conda install --file requirements.txt -c conda-forge --yes
    displayName: Install dependencies
    
  - bash: |
      source activate myEnvironment
      export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/share/miniconda/envs/myEnvironment/lib
      export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:/usr/share/miniconda/envs/myEnvironment/include
      python setup.py bdist_wheel
      pip install dist/*.whl
    displayName: Build
    
  - bash: |
      source activate myEnvironment
      pytest -vv
    displayName: Test
    
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: dist/
      artifactName: Artifacts

  - task: GithubRelease@0 
    displayName: 'Create GitHub Release'      
    inputs:
      gitHubConnection: pipeline
      repositoryName: whistlebee/harmat
      action: create
      target: $(Build.SourceVersion)
      tagSource: auto
      addChangeLog: true
      assets: dist/*
    
- job:
  displayName: macOS-10.14
  pool:
    vmImage: 'macOS-10.14'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - bash: conda create --yes --quiet --name myEnvironment
    displayName: Create Anaconda environment

  - bash: |
      source activate myEnvironment
      conda install --yes --quiet --name myEnvironment python=$PYTHON_VERSION
      conda update --all --yes
      pip install pytest pytest-azurepipelines
    displayName: Install Anaconda packages
    
  - bash: |
      source activate myEnvironment
      conda install boost-cpp -c conda-forge --yes
      conda install --file requirements.txt --yes
    displayName: Install dependencies
    
  - bash: |
      source activate myEnvironment
      export MACOSX_DEPLOYMENT_TARGET=10.9
      python setup.py bdist_wheel
      pip install dist/*.whl
    displayName: Build
    
  - bash: |
      source activate myEnvironment
      pytest -vv
    displayName: Test
    
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: dist/
      artifactName: Artifacts

  - task: GithubRelease@0 
    displayName: 'Create GitHub Release'      
    inputs:
      gitHubConnection: pipeline
      repositoryName: whistlebee/harmat
      action: create
      target: $(Build.SourceVersion)
      tagSource: auto
      addChangeLog: true
      assets: dist/*
