jobs:
- job:
  displayName: ubuntu-16.04
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - bash: conda create --yes --quiet --name myEnvironment
    displayName: Create Anaconda environment

  - bash: |
      source activate myEnvironment
      conda install --yes --quiet --name myEnvironment python=$PYTHON_VERSION
      pip install pytest pytest-azurepipelines
    displayName: Install Anaconda packages
    
  - bash: |
      source activate myEnvironment
      conda install boost --yes
      conda install --file requirements.txt --yes
    displayName: Install dependencies
    
  - bash: |
      source activate myEnvironment
      python setup.py bdist_wheel
      pip install dist/*.whl
    displayName: Build
    
  - bash: |
      source activate myEnvironment
      pytest -vv
    displayName: Test
    
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: dist/
      artifactName: Artifacts

  - task: GithubRelease@0 
    displayName: 'Create GitHub Release'      
    inputs:
      gitHubConnection: harmat
      repositoryName: whistlebee/harmat
      action: create
      target: $(Build.SourceVersion)
      tagSource: auto
      addChangeLog: true
      assets: dist/*
    
- job:
  displayName: macOS-10.13
  pool:
    vmImage: 'macOS-10.13'
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - bash: conda create --yes --quiet --name myEnvironment
    displayName: Create Anaconda environment

  - bash: |
      source activate myEnvironment
      conda install --yes --quiet --name myEnvironment python=$PYTHON_VERSION
      pip install pytest pytest-azurepipelines
    displayName: Install Anaconda packages
    
  - bash: |
      source activate myEnvironment
      conda install boost --yes
      conda install --file requirements.txt --yes
    displayName: Install dependencies
    
  - bash: |
      source activate myEnvironment
      python setup.py bdist_wheel
      pip install dist/*.whl
    displayName: Build
    
  - bash: |
      source activate myEnvironment
      pytest -vv
    displayName: Test
    
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: dist/
      artifactName: Artifacts

  - task: GithubRelease@0 
    displayName: 'Create GitHub Release'      
    inputs:
      gitHubConnection: harmat
      repositoryName: whistlebee/harmat
      action: create
      target: $(Build.SourceVersion)
      tagSource: auto
      addChangeLog: true
      assets: dist/*
