name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        python-version: [3.9]
    name: Python ${{ matrix.python-version }} ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          mamba-version: "*"
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
      - name: Install dependencies
        run: |
          conda install --file requirements.txt
          conda install boost-cpp
      - name: Conda info
        run: |
          conda info
          conda list
      - name: Build
        run: |
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib
          export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:$CONDA_PREFIX/include
          python setup.py install
      - name: Run test
        run: |
          pytest -vv
